homeassistant: true
permit_join: false
experimental:
  livolo: true
advanced:
  channel: 26
  last_seen: ISO_8601
serial:
  port: /dev/ttyACM0
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://localhost'
  user: homeassistant
  password: privet
devices:
  '0x00158d0002f2ed69':
    friendly_name: bedroom
    retain: true
  '0x00158d0002f2ed1f':
    friendly_name: livingroom
    retain: true
  '0x00124b001838b864':
    friendly_name: kitchen_light
    retain: true
  '0x00158d0002e2ccea':
    friendly_name: bedroom_lamps_switch
    retain: true
  '0x00124b00180358d3':
    friendly_name: hallway_light_entrance
    retain: true
  '0x00124b001838cdfd':
    friendly_name: bathroom_switch
    retain: true
  '0x00124b001803573a':
    friendly_name: livingroom_light
    retain: true
  '0x00124b0018028fd6':
    friendly_name: bedroom_light
    retain: true
  '0x00124b001838d640':
    friendly_name: hallway_light_dup
    retain: true
  '0x00124b001838d9fe':
    friendly_name: hallway_light
    retain: true
  '0x00158d0002c92aef':
    friendly_name: livingroom_lamp_switch
    retain: true
  '0x000d6ffffe4872d8':
    friendly_name: kitchen_lamp
    retain: true
    debounce: 0.1
  '0x000d6ffffe0e63cd':
    friendly_name: livingroom_lamp1
    retain: true
    debounce: 0.1
  '0x000d6ffffe4860dd':
    friendly_name: livingroom_lamp2
    retain: true
    debounce: 0.1
  '0xd0cf5efffefc876e':
    friendly_name: bedroom_lamp_left
    retain: true
    debounce: 0.1
  '0x000d6ffffe12c0c2':
    friendly_name: bedroom_lamp_right
    retain: true
    debounce: 0.1
  '0x000b57fffed836d2':
    friendly_name: kitchen_lamp_small
    retain: true
    debounce: 0.1
  '0x00158d0002043eb9':
    friendly_name: bedroom_lamp_left_switch
    retain: true
  '0x00158d0002008fd6':
    friendly_name: bedroom_lamp_right_switch
    retain: true
  '0x00158d0002bfea67':
    friendly_name: kitchen_lamp_switch
    retain: true
  '0x00158d000309939d':
    friendly_name: washer_door
    retain: true
  '0x00158d0002821ea3':
    friendly_name: bathroom_leak
    retain: true
  '0x00158d0002c957d1':
    friendly_name: dishwasher_door
    retain: true
  '0x00158d00028a09a5':
    friendly_name: kitchen_leak
    retain: true
  '0x00158d0002c9584d':
    friendly_name: entrance_door
    retain: true
  '0x00124b00194a06da':
    friendly_name: bedroom_router
    retain: true
