esphome:
  name: cat_fountain
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: cat-fountain
    password: !secret wifi_password

captive_portal:
logger:
api:
ota:

sensor:
  - platform: adc
    pin: GPIO32
    name: cat_fountain_illuminance
    update_interval: 1s
    attenuation: 11db
    unit_of_measurement: lx
    filters:
      - delta: 0.01
      - lambda: return (x / 10000.0) * 2000000.0;
